### ISSUE TITLE
You should Add Jquery as well :)

### ISSUE THREAD

**Issue by manjula-dube** [rwieruch/why-frameworks-matter#1]

**Comment by rwieruch** [comment]
That would be perfect! 👍

**Comment by manjula-dube** [comment]
I can work on the jQuery part every developer goes through it :)

**Comment by rwieruch** [comment]
Great! Reach out if you need any help :)

**Comment by rwieruch** [comment]
@manjula91 I made a couple of changes to the namings of the functions and split up the JavaScript example into vanilla JS and jQuery.

**Comment by antonkuleshov** [comment]
@rwieruch I tried to commit jQuery Contribution but I got "Unable to access" message. If you need this version, please contact to me )

**Comment by rwieruch** [comment]
Super nice of you contributing to this project! You need to go the official route of forking and creating a PR with your changes for this project: https://help.github.com/articles/creating-a-pull-request-from-a-fork Otherwise everyone would be able to push changes without permission to any GitHub repository :)

**Comment by antonkuleshov** [comment]
Ok, sure, I am create pull request from fork

**Comment by rwieruch** [comment]
Done 💯
